#!/bin/bash
set -e

echo "IM RUNNING CONFIGURATION NOW $POSTGRES_PASSWORD $POSTGRES_USER"

PGPASSWORD=$POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER <<-EOSQL
	CREATE DATABASE school;
EOSQL